
const Page: React.FC = () => {
    return <div>
        Top <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        home <br/>
        Bottom <br/>  
    </div>
}

export default {
    element: Page,
    title: "HI!"
}